name: DockerImageCI
  
on:
  workflow_dispatch:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   # - name: Build the Docker image
     # run: docker build . --file Dockerfile --tag tonytdj/webapp:${{github.run_number}}
     
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: Build and push
      run : docker build -t tonytdj/webapp:${{github.run_number}} --pull=true --file=./Dockerfile ${{ github.workspace }} && docker push tonytdj/webapp:${{github.run_number}}
